# Generated by Django 4.2.1 on 2023-07-09 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256)),
                ('adderss', models.CharField(max_length=256)),
                ('company_phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('statement', models.ImageField(upload_to='statement_Company/')),
                ('payment_note_image', models.ImageField(upload_to='payment_note_image_Company/')),
                ('company_services', models.TextField(max_length=1024)),
                ('company_logo', models.ImageField(upload_to='company_logo/')),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('can_activate', models.BooleanField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
