# Generated by Django 4.2.1 on 2023-07-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_company_can_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
