# Generated by Django 4.2.1 on 2023-07-24 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_car_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpart',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='parts_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
